### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by J-Uhero** [antonlep/shortest-path#1]
# Vertaisarvio

Projektia ladattu ja katselmoitu 23.04. klo 18.

Projekti näyttäisi olevan erittäin hyvällä mallilla. Algortitmit pystyy itse ajamaan, ne toimivat niin kuin kuuluukin ja visualisaatiotkin löytyvät erillisiltä kuvilta. Määrittelydokumentissa mainittujen algoritmien eli Dijksran ja JPS:n lisäksi on toteutettu vielä A*. Yksikkötestausta  on tehty kattavasti ja testausdokumentti on monipuolinen sisältäen dokumentaatiota yksikkötestauksen kattavuudesta, algoritmien toimintaa visualisoituna ja suorituskykytestausta diagrammien kera.

Koodi on pääasiassa siistiä ja nimeäminen ymmärrettävää ja asianmukaista. Omaan makuuni kaipaisin hieman enemmän koodin kommentointia, jotta sen seuraaminen ja ymmärtäminen olisi helpompaa, vaikka suurimmalta osin kuitenkin eri luokkien ja funktioiden alussa on kerrottu ymmärrettävästi, mihin niitä käytetään. Esimerkiksi Algorithm-luokassa/tiedostossa ei ole kuin funktiokohtaista docstring-kommentointia ja nimenä luokan käyttötarkoitus ei heti aukene ennen kuin tutustuu tarkemmin varsinaisten algoritmiluokkien toimintaan. Sama heuristic-funktio, joka on tässä luokassa tyhjä, näyttäisi löytyvän A_star- ja JPS-luokista, joten ehkä sen voisi keskittää vaikka tänne.  Suurimmalta osin kuitenkin eri luokkien ja funktioiden alussa on kerrottu ymmärrettävästi, mihin niitä käytetään ja algoritmin toiminta selkenee koodia seuraamalla, ainakin jos algoritmien toiminnasta on jo ennalta ymmärrystä. 

JPS-algoritmin funktiot prune ja forced_neighbor sisältävät lähes toisteista koodia ja paljon peräkkäisiä ja sisäkkäisiä samanhenkisiä ehtolauseita. Tämä voi olla perusteltua mikäli algoritmin mahdollisimman tehokas toiminta sitä vaatii, mutta mietin, että niiden siistiminen voisi ehkä olla myös mahdollista ilman, että tehokkuus juuri kärsisi. Eri ehtolauseissa on kuitenkin varsin samanhenkisiä tarkistuksia ja niistä seuraavia toimenpiteitä, jotka voivat osa sisältää samanlaisia säännönmukaisuuksia. Koodikatselmointihetkellä olitkin maininnut JPS:n siistimisen yhdeksi tulevan viikon 6 tavoitteistasi, joten tämä lieneekin jo agendalla ja siitä huomauttaminen ehkä turhaa.

Tällä hetkellä ohjelma ajetaan komentorivikomennoilla, joihin kirjataan käytettävä algoritmi, alku- ja loppupiste ja karttakuvan nimi. Mielestäni tämä on ihan käypä tapa ajaa ohjelma, mutta toki tällekin voi olla helppokäyttöisempiä vaihtoehtoja, myös tämä palvelee tarkoitustaan asianmukaisesti. On hyvä, että suorittaminen palauttaa keskeiset algoritmin toimintaan liittyvät tiedot kuten suoritusajan ja käytyjen solmujen määrän suoraan terminaliin ja että reitistä piirretty kuva ja tarkemmat tiedot löytyvät erikseen, vaikka toki niiden kaivaminen esille vaatii oman pienen vaivansa.

Joka tapauksessa projekti on erittäin hyvällä mallilla ja valmiin oloinen vaatien enää korkeintaan pintasilausta. Tätä oli ilo tutkia.

Vaikka projektisi on toteutettu englanniksi, kirjoitin tämän arvioinnin nyt suomeksi, koska huomasin sinulla olleen muita suomenkielisiä projekteja aiemmin.

**Comment by antonlep** [comment]
Kiitos kommenteista, hyviä huomioita!
